[build]
  # O comando atualizado que o Netlify vai rodar
  command = "bash scripts/build.sh"
  
  # A pasta que o Netlify deve publicar
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
  NETLIFY_SKIP_SECRET_SCANNING = "true"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:; connect-src *;"
    Service-Worker-Allowed = "/"
